---
outputs:
- Reveal
title: Scientific R Markdown blog?
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Scientific blogging with R Markdown

:wave: Welcome!

---

I'm Maëlle, I like R, blogging and science.

{{% fragment %}}

:house: https://masalmon.eu

{{% /fragment %}}


---

# Why blog?

---

* Notes for future you

* Passion for sharing?

* Opportunities

---

Teaching this course is an opportunity I got from blogging but blogging is not a pyramid scheme :wink:

---

# Why create blog?

What if I don't really want to blog regularly?

<!--html_preserve-->

- {{% fragment %}}Have a platform to share stuff when you need to.{{% /fragment %}}
- {{% fragment %}}Portfolio. In particular, imagine someone recommending you for a thing.{{% /fragment %}}

<!--/html_preserve-->
---

# Why Rmd for blogging?

- {{% fragment %}}Data analysis with R{{% /fragment %}}
- {{% fragment %}}Blogging about R{{% /fragment %}}
- {{% fragment %}}R as an utility tool e.g. to generate text from structured data{{% /fragment %}}
- {{% fragment %}}knitr supports other languages...{{% /fragment %}}

---

# WHAT is is a scientific Rmd blog?

---

IMHO :smile_cat:

I'll list criteria so we have something to compare our adventures to.

---

# Tech part

<!--html_preserve-->

* {{% fragment %}}Easy way to update from Rmd without too much copy-pasting{{% /fragment %}}

* {{% fragment %}}Fits into your existing workflow or uses things you want to learn and invest time in{{% /fragment %}}

* {{% fragment %}}Code, syntax highlighting{{% /fragment %}}

* {{% fragment %}}Modern tooling (html5? mobile friendly?){{% /fragment %}}

<!--/html_preserve-->
---

# Science part

* {{% fragment %}}References from a .bib file{{% /fragment %}}

* {{% fragment %}}Easy way to cite posts?{{% /fragment %}}

* {{% fragment %}}Equations {{% /fragment %}}

* {{% fragment %}}Content. Blog about science, or stuff relevant to science&co (e.g. comparisons of way to fit and present linear models in R).{{% /fragment %}}

---

# Human part

* {{% fragment %}}Accessible. Alt text, contrast. Don't add gate-keeping to science.{{% /fragment %}}

* {{% fragment %}}You OWN it. Content, URL (no commercial service, no employer).{{% /fragment %}}

* {{% fragment %}}Allows for interactions (social media? commenting?){{% /fragment %}}

* {{% fragment %}}Costs a few dollars a month at most.{{% /fragment %}}

---

# Let's go

* {{% fragment %}}distill{{% /fragment %}}

* {{% fragment %}}Hugo&hugodown{{% /fragment %}}

* {{% fragment %}}WordPress{{% /fragment %}}

* {{% fragment %}}Debrief{{% /fragment %}}

---

# We'll start with a website tour

https://tiny.cc/rmd-blog
