---
outputs:
- Reveal
title: distill
hidden: true
layout: list
weight: 1
output: hugodown::md_document
countdown: true
---

# Distill

---

[Distill](rstudio.github.io/distill/) is both a framework and an R package.

> Distill for R Markdown is a web publishing format optimized for scientific and technical communication.

---

* Output format for single documents

* Websites

* Blogs, like websites but with blog posts than aren't re-rendered automatically.

---

Helpers like `distill::create_post()`.

---

:train: Time for a demo!

---

Scientific Rmd Blog Checklist

* [x] R Markdown
* [x] Syntax highlighting (for all knitr-supported languages)
* [x] Modern
* [x] .bib
* [x] Citation for posts
* [x] Equations

---

# Sustainability

Created by:

```{r, echo=FALSE, results="asis"}
glue::glue_collapse(
  trimws(
  gsub("<.*>", "",
  desc::desc_get_author(file = find.package("distill"), role = "aut")
  )
  ), 
  sep = ", ")
```

Used for [RStudio AI blog](https://blogs.rstudio.com/ai/), in particular.

Active development.

---

# Follow developments?

* Read the changelog when updating the package?

* [Watch development on GitHub](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository)?

* Subscribe to the [issues](https://github.com/rstudio/distill/issues) that are interesting to you: [search](https://github.com/rstudio/distill/issues/9), [ORCID](https://github.com/rstudio/distill/issues/21), etc.?

---

# Questions, comments?

Write them in the pad!

---

# Time for a break :coffee:

<!--html_preserve-->

<div id="timer_5ee3a3da" class="countdown" style="top:100;left:0;" data-warnwhen="0">

<code class="countdown-time"><span class="countdown-digits minutes">05</span><span class="countdown-digits colon">:</span><span class="countdown-digits seconds">00</span></code>

</div>

<!--/html_preserve-->