---
title: Notes from the demo
menuTitle: Demo
weight: 5
slides: true
output: hugodown::md_document
---



- create blog (from RStudio Create New Project, not `distill::create_blog()`).

- what's in the folder now?

- show website in local browser.

- change site but not URL, and about. change citations: true!!!

- rebuild the site via RStudio build button or `rmarkdown::render_site()`.

- show website in local browser.

- `usethis::use_git()`

- `usethis::use_github()`

- edit and knit welcome. including author info!!

- commit

- rebuild the site via RStudio build button or `rmarkdown::render_site()`.

- look what changed

- show website in local browser.

- look at post html in _posts and _site. mention JavaScript

- commit

- add a post with `distill::create_post()`. knit, look what changed this time. Mention [post workflows](https://rstudio.github.io/distill/blog_workflow.html!

- add references

- add latex

- put website online via Netlify drag and drop.

- put website online via Netlify+GitHub. mention there are other options.

- add base_url to site config, show citations metadata is added.

- Netlify drag and drop / GitHub repo.

- Some minimal styling. 

- mention git checkout -b and [the distill docs about blog post workflows](https://rstudio.github.io/distill/blog_workflow.html).

- add Twitter&GitHub