---
outputs:
- Reveal
title: Promotion
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Promote your blog

---

# Put its URL everywhere!

Your ORCID profile, Twitter profile, GitHub profile, etc.

No dead ends please!

---

# R Weekly

Weekly newsletter featuring links to blog posts but also slidedecks, etc., about R.

* One-off sharing: [web form](https://rweekly.org/submit), [PRs](https://github.com/rweekly/rweekly.org).

* Add your RSS feed via the [web form](https://rweekly.org/submit).

---

# R Bloggers

Ingests the entire feed and repost posts.

It can take time from [feed submission](https://www.r-bloggers.com/add-your-blog/) to feed validation.

---

# Social media

E.g. Twitter.

Write a clear text, post URL, add a few hashtags, image (or carefully crafted infographics?) + alternative text.

---

# Interact with readers

On social media?

In comments? For Hugo, [Utteranc.es as an alternative to Disqus](https://masalmon.eu/2019/10/02/disqus/).

---

# Negative feedback

(not constructive feedback)

Have a support system.

You don't have to respond publicly, or at all.

If _you_ were wrong, listen and do better.

---

# SEO

Search Engine Optimization

* Add links to your post

* Read resources by marketers

---

# Analytics

* Do you need numbers? E.g. if you blog at work.

* Are you ok using Google Analytics? 

* GDPR :wink:

* Alternatives? [Fathom](https://usefathom.com/)? Others?