---
outputs:
- Reveal
title: Conclusion
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Scientific blogging with R Markdown

:sob: Nearly time to say goodbye!

---

* distill: perfect, not flexible

* Hugo&hugodown: very flexible (too flexible?), changes fast, experimental R package

* WordPress&goodpress: also flexible, even more experimental R package

---

# What to choose

* distill

* Hugo Academic with `hugodown::create_site_academic()`

* WordPress if you already use WordPress?

---

# What to choose

Start by playing! Don't commit right away.

Does any of you want to say what they'd choose and why?

---

# True for all

* Read the docs and follow development! :eyes:

* Backup! :warning:

---

# Change your mind?

* Migration tools

* `yaml`, `commonmark` packages, etc.

* Redirects! URLs are important. 404 page.

---

# Have fun!

If you're worried about blogging, find a blogging buddy to read your drafts?

Make efforts but don't be perfectionist.

---

# Setup is not fun

* With helpers, setup is smoother

* But in general setup = learning a new thing, hard but then you get used to it!

---

# Regular blogging?

No you don't have to unless you call your blog "the daily blog" or so. :wink:

Only write if you enjoy it!

---

# Tell me

* Questions this afternoon  :raising_hand:

* Issues in the [website repo](https://github.com/maelle/rmd-blogging-course/issues) for questions  :raising_hand:

* [Tweets](https://twitter.com/ma_salmon)/emails to show me your websites. :star:
